<?php

namespace Tests\Unit\Classes\Controller\Api;

use Services\Api\Reply;
use Test_Unit;

class ReplyTest extends Test_Unit
{
    /** @var Reply */
    private $reply;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->reply = new Reply();
    }

    /** @test */
    public function build__ResponseOk()
    {
        $data = [
            "example" => "array message"
        ];

        $response = $this->reply->buildResponseOk($data);

        list('status' => $response_status, 'data' => $response_data) = $response;

        $this->assertSame($response_status, Reply::STATUS_SUCCESS);

        $this->assertSame($response_data, $data);
    }

    /** @test */
    public function build__ResponseError()
    {
        $error_data = [
            "error_one" => "This is an error",
            "error_two" => "Second error"
        ];

        $response_types = [
            Reply::BAD_REQUEST,
            Reply::NOT_FOUND,
            Reply::OK,
            Reply::UNAUTHORIZED
        ];

        $key = array_rand($response_types, 1);

        $response = $this->reply->buildResponseError($response_types[$key], $error_data);

        list('response' => $response_data, 'status' => $response_status) = $response;

        $this->assertSame($response_status, $response_types[$key]['status']);

        $this->assertSame($response_data['status'], Reply::STATUS_ERROR);


        $errors = $response_data['errors'];

        $this->assertSame($errors['title'], $response_types[$key]['title']);

        $this->assertSame($errors['message'], $error_data);
    }
}
