<?php


use Services\Api\Security;
use Repositories\WhitelabelRepository;

class Tests_Feature_Classes_Controller_Api_Security extends Test_Feature
{
    /** @var Security */
    private $security;

    /** @var Whitelabel */
    private $whitelabel;

    /** @var WhitelabelRepository */
    private $whitelabelRepository;

    const EXAMPLE_URL_WITH_API = "api.lottopark.loc";
    const EXAMPLE_URL_WITHOUT_API_PREFIX = "lottopark.loc";

    const EXAMPLE_URL_WITH_OTHER_PREFIX = "without.lottopark.loc";

    public function __construct()
    {
        parent::__construct();
        $this->whitelabelRepository = Container::get(WhitelabelRepository::class);
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->build_security();
    }

    public function test_is_api_route_not_accessible()
    {
        $url_source = Lotto_Settings::getInstance()->get("routing_source");
        $deny_access = "api" !== $url_source;

        $response_from_method = $this->security->isApiRouteNotAccessible();

        $this->assertSame($deny_access, $response_from_method);
    }

    public function test_check_if_url_not_begin_from_api()
    {
        $check_method = $this->security->checkUrlNotBeginFromApi();

        $this->assertFalse($check_method);

        $_SERVER['HTTP_HOST'] = self::EXAMPLE_URL_WITH_OTHER_PREFIX;

        $this->security = new Security($this->whitelabelRepository);

        $check_method = $this->security->checkUrlNotBeginFromApi();

        $this->assertTrue($check_method);

        $this->build_security();
    }

    public function test_get_domain_without_api_prefix()
    {
        $domain = $this->security->getDomainWithoutApiPrefix();

        $this->assertSame($domain, self::EXAMPLE_URL_WITHOUT_API_PREFIX);
    }

    public function test_get_whitelabel()
    {
        $whitelabel = $this->security->getWhitelabel();
        $this->assertSame($this->whitelabel->to_array(), $whitelabel->to_array());
    }

    private function build_security()
    {
        $_SERVER['HTTP_HOST'] = self::EXAMPLE_URL_WITH_API;

        $this->security = new Security($this->whitelabelRepository);

        $domain = self::EXAMPLE_URL_WITHOUT_API_PREFIX;

        $whitelabel = $this->whitelabelRepository->findOneByDomain($domain);

        $this->whitelabel = $whitelabel;
    }
}
