<?php

use Core\App;
use Fuel\Core\Fuel;
use Helpers\Wordpress\LanguageHelper;

$continue_on = [];
$continue_on[Fuel::PRODUCTION] = [
    E_NOTICE,
    E_WARNING,
    E_DEPRECATED,
    E_STRICT
];

// do not stop on wordpress deprecated errors
// when WP_DEBUG is set to true
$continue_on[Fuel::DEVELOPMENT] = [
    E_USER_DEPRECATED,
    E_NOTICE,
    E_USER_NOTICE,
];

$continue_on[Fuel::STAGING] = $continue_on[Fuel::DEVELOPMENT];

$logDirPath = $_ENV['LOG_PATH'] ?? '/var/log/php/whitelotto/';
$serverType = $_ENV['SERVER_TYPE'];

if (Fuel::$env === Fuel::TEST) {
    $serverType = Fuel::TEST;
}

switch ($serverType) {
    case $serverType === App::TEXTS:
        $_ENV['LOG_PATH'] .= App::TEXTS . '/';
        break;
    case $serverType === App::TEST:
        $_ENV['LOG_PATH'] .= 'tests/';
        break;
    case $serverType === App::PRE_MASTER:
        $_ENV['LOG_PATH'] .= App::PRE_MASTER . '/';
        break;
}
$logDirPath = $_ENV['LOG_PATH'];
$domain = Container::get('domain');

return [

    /**
     * base_url - The base URL of the application.
     * MUST contain a trailing slash (/)
     *
     * You can set this to a full or relative URL:
     *
     *     'base_url' => '/foo/',
     *     'base_url' => 'http://foo.com/'
     *
     * Set this to null to have it automatically detected.
     * ! IMPORTANT: it is commented out and will still get resolved automatically in container-config.php
     */
    // 'base_url'  => null,

    /**
     * url_suffix - Any suffix that needs to be added to
     * URL's generated by Fuel. If the suffix is an extension,
     * make sure to include the dot
     *
     *     'url_suffix' => '.html',
     *
     * Set this to an empty string if no suffix is used
     */
    // 'url_suffix'  => '',

    /**
     * index_file - The name of the main bootstrap file.
     *
     * Set this to 'index.php if you don't use URL rewriting
     */
    // 'index_file' => false,

    // 'profiling' => false,

    /**
     * Default location for the file cache
     */
    // 'cache_dir'       => APPPATH.'cache/',

    /**
     * Settings for the file finder cache (the Cache class has it's own config!)
     */
    // 'caching'         => false,
    // 'cache_lifetime'  => 3600, // In Seconds

    /**
     * Callback to use with ob_start(), set this to 'ob_gzhandler' for gzip encoding of output
     */
    // 'ob_callback'  => null,

    'errors'  => [
        // Which errors should we show, but continue execution? You can add the following:
        // E_NOTICE, E_WARNING, E_DEPRECATED, E_STRICT to mimic PHP's default behaviour
        // (which is to continue on non-fatal errors). We consider this bad practice.
        'continue_on'  => $continue_on[Fuel::$env] ?? [],
        // How many errors should we show before we stop showing them? (prevents out-of-memory errors)
        // 'throttle'     => 10,
        // Should notices from Error::notice() be shown?
        // 'notices'      => true,
        // Render previous contents or show it as HTML?
        // 'render_prior' => false,
    ],

    /**
     * Localization & internationalization settings
     */
    'language'           => LanguageHelper::DEFAULT_LANGUAGE_SHORTCODE, // Default language
    'language_fallback'  => LanguageHelper::DEFAULT_LANGUAGE_SHORTCODE, // Fallback language when file isn't available for default language
    'locale'             => null, // PHP set_locale() setting, null to not set

    /**
     * Internal string encoding charset
     */
    'encoding'  => 'UTF-8',

    /**
     * DateTime settings
     *
     * server_gmt_offset	in seconds the server offset from gmt timestamp when time() is used
     * default_timezone		optional, if you want to change the server's default timezone
     */
    // 'server_gmt_offset'  => 0,
    'default_timezone'   => 'UTC',

    /**
     * Logging Threshold.  Can be set to any of the following:
     *
     * Fuel::L_NONE
     * Fuel::L_ERROR
     * Fuel::L_WARNING
     * Fuel::L_DEBUG
     * Fuel::L_INFO
     * Fuel::L_ALL
     */
    //'log_threshold'    => Fuel::L_ALL,
    'log_path'         => $logDirPath,
    // 'log_date_format'  => 'Y-m-d H:i:s',

    /**
     * Security settings
     */
    'security' => [
        // 'csrf_autoload'            => false,
        // 'csrf_autoload_methods'    => array('post', 'put', 'delete'),
        // 'csrf_bad_request_on_fail' => false,
        // 'csrf_auto_token'          => false,
        'csrf_token_key'           => 'lotto_csrf_token_2',
        'csrf_expiration'          => 600,

        /**
         * A salt to make sure the generated security tokens are not predictable
         */
        'token_salt'            => $_ENV['SECURITY_TOKEN_SALT'],

        /**
         * Allow the Input class to use X headers when present
         *
         * Examples of these are HTTP_X_FORWARDED_FOR and HTTP_X_FORWARDED_PROTO, which
         * can be faked which could have security implications
         */
        // 'allow_x_headers'       => false,

        /**
         * This input filter can be any normal PHP function as well as 'xss_clean'
         *
         * WARNING: Using xss_clean will cause a performance hit.
         * How much is dependant on how much input data there is.
         */
        'uri_filter'       => ['htmlentities'],

        /**
         * This input filter can be any normal PHP function as well as 'xss_clean'
         *
         * WARNING: Using xss_clean will cause a performance hit.
         * How much is dependant on how much input data there is.
         */
        //'input_filter'  => array(),

        /**
         * This output filter can be any normal PHP function as well as 'xss_clean'
         *
         * WARNING: Using xss_clean will cause a performance hit.
         * How much is dependant on how much input data there is.
         */
        'output_filter'  => [],

        /**
         * Encoding mechanism to use on htmlentities()
         */
         //'htmlentities_flags' => ENT_NOQUOTES,

        /**
         * Whether to encode HTML entities as well
         */
        // 'htmlentities_double_encode' => false,

        /**
         * Whether to automatically filter view data
         */
        // 'auto_filter_output'  => true,

        /**
         * With output encoding switched on all objects passed will be converted to strings or
         * throw exceptions unless they are instances of the classes in this array.
         */
        'whitelisted_classes' => [
            'Fuel\\Core\\Presenter',
            'Fuel\\Core\\Response',
            'Fuel\\Core\\View',
            'Fuel\\Core\\ViewModel',
            'Fuel\\Core\\Pagination',
            'Closure',
        ],

        // White Lotto: used for generating activation key
        'activation_key' => $_ENV["SECURITY_ACTIVATION_KEY"],
    ],
    /**
     * Cookie settings
     */
    'cookie' => [
        // Number of seconds before the cookie expires
        // 'expiration'  => 0,
        // Restrict the path that the cookie is available to
        // 'path'        => '/',
        // Restrict the domain that the cookie is available to
         'domain'      => '.' . $domain,
        // Only transmit cookies over secure connections
         'secure'      => true,
        // Only transmit cookies over HTTP, disabling Javascript access
         'http_only'   => true,
    ],

    /**
     * Validation settings
     */
    // 'validation' => array(
        /**
         * Whether to fallback to global when a value is not found in the input array.
         */
        // 'global_input_fallback' => true,
    // ),

    /**
     * Controller class prefix
     */
     // 'controller_prefix' => 'Controller_',

    /**
     * Routing settings
     */
    // 'routing' => array(
        /**
         * Whether URI routing is case sensitive or not
         */
        // 'case_sensitive' => true,

        /**
         *  Whether to strip the extension
         */
        // 'strip_extension' => true,
    // ),

    /**
     * To enable you to split up your application into modules which can be
     * routed by the first uri segment you have to define their basepaths
     * here. By default empty, but to use them you can add something
     * like this:
     *      array(APPPATH.'modules'.DS)
     *
     * Paths MUST end with a directory separator (the DS constant)!
     */
     'module_paths' => [
        APPPATH.'modules'.DS
     ],

    /**
     * To enable you to split up your additions to the framework, packages are
     * used. You can define the basepaths for your packages here. By default
     * empty, but to use them you can add something like this:
     *      array(APPPATH.'modules'.DS)
     *
     * Paths MUST end with a directory separator (the DS constant)!
     */
    'package_paths' => [
        PKGPATH,
    ],

    /**************************************************************************/
    /* Always Load                                                            */
    /**************************************************************************/
    'always_load' => [
        'packages' => [
            'orm',
        ],
    ],

    /**************************************************************************/
    /* Mock LCS Server - it will return random values if turned on            */
    /**************************************************************************/
    'mock_lcs' => false,

    'wordpress' => [
        'path' => $_ENV['WP_PATH'],
    ],
];
