FROM docker-repo.gginternational.work/gg-httpd AS gg-httpd

ARG PHP_VERSION
ARG DEBIAN_FRONTEND=noninteractive
    
COPY ./config/sites-available/ /etc/apache2/sites-available/

RUN a2disconf php* || true && \
    a2enconf php${PHP_VERSION}-fpm && \
    a2dissite 000-default.conf

STOPSIGNAL SIGWINCH

COPY startup-gg.sh /usr/local/bin/

ENTRYPOINT ["startup-gg.sh"]

EXPOSE 8443
CMD ["apache2ctl", "-DFOREGROUND"]
