<?php

namespace Services\Api\Slots;

use Carbon\Carbon;
use Exception;
use Fuel\Core\DB;
use Helpers_Currency;
use Models\WhitelabelUser;
use Models\SlotGame;
use Models\SlotOpenGame;
use Models\SlotTransaction;
use Models\WhitelabelSlotProvider;
use Repositories\CurrencyRepository;
use Throwable;

class TransactionService
{
    private SlotGame $slotGame;
    private SlotOpenGame $slotOpenGame;
    private WhitelabelUser $whitelabelUser;
    private WhitelabelSlotProvider $whitelabelSlotProvider;
    private CurrencyRepository $currencyRepository;

    public function __construct(CurrencyRepository $currencyRepository)
    {
        $this->currencyRepository = $currencyRepository;
    }

    public function configure(
        SlotGame $slotGame,
        SlotOpenGame $slotOpenGame,
        WhitelabelUser $whitelabelUser,
        WhitelabelSlotProvider $whitelabelSlotProvider
    ) {
        $this->slotGame = $slotGame;
        $this->slotOpenGame = $slotOpenGame;
        $this->whitelabelUser = $whitelabelUser;
        $this->whitelabelSlotProvider = $whitelabelSlotProvider;
    }

    /**
     * Return updated transaction with token generated by database side
     *
     * @param float $amount
     * @param string $currencyCode
     * @param string $action
     * @param string|null $type
     * @param string $providerTransactionId
     * @param array $additionalData
     * @return SlotTransaction
     * @throws Throwable
     */
    public function addTransaction(
        float $amount,
        string $currencyCode,
        string $action,
        ?string $type,
        string $providerTransactionId,
        array $additionalData
    ): SlotTransaction {
        $whitelabel = $this->whitelabelUser->whitelabel;
        $currency = $this->currencyRepository->findOneByCode($currencyCode);
        $transaction = new SlotTransaction();
        $transaction->slotGame = $this->slotOpenGame->slotGame;
        $transaction->slotOpenGame = $this->slotOpenGame;
        $transaction->whitelabelUser = $this->whitelabelUser;
        $transaction->whitelabelSlotProvider = $this->whitelabelSlotProvider;
        $transaction->amount = $amount;
        $transaction->currency = $currency;
        $transaction->token = DB::expr('UUID_SHORT()');

        $amountInUsd = (float)Helpers_Currency::convert_to_USD(
            $amount,
            $currencyCode,
        );
        $amountInManagerCurrency = (float)Helpers_Currency::convert_to_any(
            $amount,
            $currencyCode,
            $whitelabel->currency->code
        );

        $transaction->amountUsd = $amountInUsd;
        $transaction->amountManager = $amountInManagerCurrency;
        $transaction->action = $action;
        $transaction->type = $type;
        $transaction->providerTransactionId = $providerTransactionId;
        $transaction->createdAt = new Carbon($transaction->getTimezoneForField('createdAt'));
        $transaction->additionalData = $additionalData;
        $transaction->save();

        SlotTransaction::flush_cache();
        $transaction->reload();

        return $transaction;
    }
}
