<?php

namespace Models;

use Classes\Orm\AbstractOrmModel;
use Carbon\Carbon;
use Orm\BelongsTo;
use Orm\HasMany;

/**
 * @property int $id
 * @property int $whitelabelSlotProviderId
 * @property int $slotGameId
 * @property int $whitelabelUserId
 * @property int $currencyId
 *
 * SessionId is generated by us on game init. It is unique per each opened game
 * @property int $sessionId
 * @property Carbon $createdAt
 *
 * @property BelongsTo|WhitelabelSlotProvider $whitelabelSlotProvider
 * @property BelongsTo|SlotGame $slotGame
 * @property BelongsTo|WhitelabelUser $whitelabelUser
 * @property BelongsTo|Currency $currency
 * @property HasMany|SlotTransaction[] $slotTransactions
 */
class SlotOpenGame extends AbstractOrmModel
{
    protected static string $_table_name = 'slot_open_game';

    protected static array $_properties = [
        'id',
        'whitelabel_slot_provider_id',
        'slot_game_id',
        'whitelabel_user_id',
        'currency_id',
        'session_id',
        'created_at'
    ];

    protected $casts = [
        'id' => 'integer',
        'whitelabel_slot_provider_id' => 'integer',
        'slot_game_id' => 'integer',
        'whitelabel_user_id' => 'integer',
        'currency_id' => 'integer',
        'session_id' => 'integer',

        'created_at' => 'carbon',
    ];

    protected array $relations = [
        WhitelabelSlotProvider::class => self::BELONGS_TO,
        SlotGame::class => self::BELONGS_TO,
        WhitelabelUser::class => self::BELONGS_TO,
        SlotTransaction::class => self::HAS_MANY,
        Currency::class => self::BELONGS_TO
    ];

    protected array $timezones = [
        'created_at' => 'UTC'
    ];

    // It is very important! Do not remove this variables!
    protected static array $_belongs_to = [];
    protected static array $_has_one = [];
    protected static array $_has_many = [];
}
