<?php

namespace Fuel\Migrations;

use Database_Migration_Graceful;
use Fuel\Core\DBUtil;
use Throwable;
use Helper_Migration;

final class Delete_Lottery_Type_Id_From_Lottery_Type_Multiplier extends Database_Migration_Graceful
{
    private string $tableName = 'lottery_type_multiplier';
    private string $column = 'lottery_type_id';

    protected function up_gracefully(): void
    {
        // before drop we have to drop foreign key.
        // in try we have old foreign key (it wasn't generated by php, thats why we have it as static value)
        // in catch we have foreign key generated from down_gracefully
        try {
            DBUtil::drop_foreign_key($this->tableName, 'lottery_type_multiplier_ibfk_2');
        } catch (Throwable $e) {
            $foreignKey = Helper_Migration::generate_foreign_key($this->tableName, $this->column);
            DBUtil::drop_foreign_key($this->tableName, $foreignKey['constraint']);
        }

        DBUtil::drop_fields($this->tableName, $this->column);
    }

    protected function down_gracefully(): void
    {
        DBUtil::add_fields(
            $this->tableName,
            [
                $this->column => [
                    'type' => 'tinyint',
                    'unsigned' => true,
                    'null' => true,
                    'default' => null,
                    'after' => 'lottery_id'
                ],
            ]
        );

        $foreignKey = Helper_Migration::generate_foreign_key($this->tableName, $this->column);
        DBUtil::add_foreign_key($this->tableName, $foreignKey);
    }
}
