<?php

namespace Fuel\Tasks\Seeders;

use Helpers_Lottery;

/**
 * Zambia Integration seeder.
 */
final class Flutterwave_Africa extends Seeder
{
    use \Without_Foreign_Key_Checks,
        \Without_Tables_On_Production;

    protected function columnsStaging(): array
    {
        return [
            'payment_method' => ['id', 'name'],
            'payment_method_supported_currency' => ['payment_method_id', 'code'],
        ];
    }

    protected function rowsStaging(): array
    {
        return [
            'payment_method' => [
                [22, 'Flutterwave Africa']
            ],
            'payment_method_supported_currency' => [
                [22, 'USD'],
                [22, 'AED'],
                [22, 'AFN'],
                [22, 'ALL'],
                [22, 'AMD'],
                [22, 'ANG'],
                [22, 'AOA'],
                [22, 'ARS'],
                [22, 'AUD'],
                [22, 'AWG'],
                [22, 'AZN'],
                [22, 'BAM'],
                [22, 'BBD'],
                [22, 'BDT'],
                [22, 'BGN'],
                [22, 'BIF'],
                [22, 'BMD'],
                [22, 'BND'],
                [22, 'BOB'],
                [22, 'BRL'],
                [22, 'BSD'],
                [22, 'BWP'],
                [22, 'BZD'],
                [22, 'CAD'],
                [22, 'CDF'],
                [22, 'CHF'],
                [22, 'CLP'],
                [22, 'CNY'],
                [22, 'COP'],
                [22, 'CRC'],
                [22, 'CVE'],
                [22, 'CZK'],
                [22, 'DJF'],
                [22, 'DKK'],
                [22, 'DOP'],
                [22, 'DZD'],
                [22, 'EGP'],
                [22, 'ETB'],
                [22, 'EUR'],
                [22, 'FJD'],
                [22, 'FKP'],
                [22, 'GBP'],
                [22, 'GEL'],
                [22, 'GIP'],
                [22, 'GMD'],
                [22, 'GNF'],
                [22, 'GTQ'],
                [22, 'GYD'],
                [22, 'HKD'],
                [22, 'HNL'],
                [22, 'HRK'],
                [22, 'HTG'],
                [22, 'HUF'],
                [22, 'IDR'],
                [22, 'ILS'],
                [22, 'INR'],
                [22, 'ISK'],
                [22, 'JMD'],
                [22, 'JPY'],
                [22, 'KES'],
                [22, 'KGS'],
                [22, 'KHR'],
                [22, 'KMF'],
                [22, 'KRW'],
                [22, 'KYD'],
                [22, 'KZT'],
                [22, 'LAK'],
                [22, 'LBP'],
                [22, 'LKR'],
                [22, 'LRD'],
                [22, 'LSL'],
                [22, 'MAD'],
                [22, 'MDL'],
                [22, 'MGA'],
                [22, 'MKD'],
                [22, 'MMK'],
                [22, 'MNT'],
                [22, 'MOP'],
                [22, 'MRO'],
                [22, 'MUR'],
                [22, 'MVR'],
                [22, 'MWK'],
                [22, 'MXN'],
                [22, 'MYR'],
                [22, 'MZN'],
                [22, 'NAD'],
                [22, 'NGN'],
                [22, 'NIO'],
                [22, 'NOK'],
                [22, 'NPR'],
                [22, 'NZD'],
                [22, 'PAB'],
                [22, 'PEN'],
                [22, 'PGK'],
                [22, 'PHP'],
                [22, 'PKR'],
                [22, 'PLN'],
                [22, 'PYG'],
                [22, 'QAR'],
                [22, 'RON'],
                [22, 'RSD'],
                [22, 'RUB'],
                [22, 'RWF'],
                [22, 'SAR'],
                [22, 'SBD'],
                [22, 'SCR'],
                [22, 'SEK'],
                [22, 'SGD'],
                [22, 'SHP'],
                [22, 'SLL'],
                [22, 'SOS'],
                [22, 'SRD'],
                [22, 'STD'],
                [22, 'SZL'],
                [22, 'THB'],
                [22, 'TJS'],
                [22, 'TOP'],
                [22, 'TRY'],
                [22, 'TTD'],
                [22, 'TWD'],
                [22, 'TZS'],
                [22, 'UAH'],
                [22, 'UGX'],
                [22, 'UYU'],
                [22, 'UZS'],
                [22, 'VND'],
                [22, 'VUV'],
                [22, 'WST'],
                [22, 'XAF'],
                [22, 'XCD'],
                [22, 'XOF'],
                [22, 'XPF'],
                [22, 'YER'],
                [22, 'ZAR'],
                [22, 'ZMW'],
            ],
        ];
    }
}
