<?php

namespace Fuel\Tasks\Seeders;

use Helpers_Lottery;

/**
 * Zambia Integration seeder.
 */
final class Flutterwave extends Seeder
{
    use \Without_Foreign_Key_Checks,
        \Without_Tables_On_Production;

    protected function columnsStaging(): array
    {
        return [
            'payment_method' => ['id', 'name'],
            'payment_method_supported_currency' => ['payment_method_id', 'code'],
        ];
    }

    protected function rowsStaging(): array
    {
        return [
            'payment_method' => [
                [21, 'Flutterwave']
            ],
            'payment_method_supported_currency' => [
                [21, 'USD'],
                [21, 'AED'],
                [21, 'AFN'],
                [21, 'ALL'],
                [21, 'AMD'],
                [21, 'ANG'],
                [21, 'AOA'],
                [21, 'ARS'],
                [21, 'AUD'],
                [21, 'AWG'],
                [21, 'AZN'],
                [21, 'BAM'],
                [21, 'BBD'],
                [21, 'BDT'],
                [21, 'BGN'],
                [21, 'BIF'],
                [21, 'BMD'],
                [21, 'BND'],
                [21, 'BOB'],
                [21, 'BRL'],
                [21, 'BSD'],
                [21, 'BWP'],
                [21, 'BZD'],
                [21, 'CAD'],
                [21, 'CDF'],
                [21, 'CHF'],
                [21, 'CLP'],
                [21, 'CNY'],
                [21, 'COP'],
                [21, 'CRC'],
                [21, 'CVE'],
                [21, 'CZK'],
                [21, 'DJF'],
                [21, 'DKK'],
                [21, 'DOP'],
                [21, 'DZD'],
                [21, 'EGP'],
                [21, 'ETB'],
                [21, 'EUR'],
                [21, 'FJD'],
                [21, 'FKP'],
                [21, 'GBP'],
                [21, 'GEL'],
                [21, 'GIP'],
                [21, 'GMD'],
                [21, 'GNF'],
                [21, 'GTQ'],
                [21, 'GYD'],
                [21, 'HKD'],
                [21, 'HNL'],
                [21, 'HRK'],
                [21, 'HTG'],
                [21, 'HUF'],
                [21, 'IDR'],
                [21, 'ILS'],
                [21, 'INR'],
                [21, 'ISK'],
                [21, 'JMD'],
                [21, 'JPY'],
                [21, 'KES'],
                [21, 'KGS'],
                [21, 'KHR'],
                [21, 'KMF'],
                [21, 'KRW'],
                [21, 'KYD'],
                [21, 'KZT'],
                [21, 'LAK'],
                [21, 'LBP'],
                [21, 'LKR'],
                [21, 'LRD'],
                [21, 'LSL'],
                [21, 'MAD'],
                [21, 'MDL'],
                [21, 'MGA'],
                [21, 'MKD'],
                [21, 'MMK'],
                [21, 'MNT'],
                [21, 'MOP'],
                [21, 'MRO'],
                [21, 'MUR'],
                [21, 'MVR'],
                [21, 'MWK'],
                [21, 'MXN'],
                [21, 'MYR'],
                [21, 'MZN'],
                [21, 'NAD'],
                [21, 'NGN'],
                [21, 'NIO'],
                [21, 'NOK'],
                [21, 'NPR'],
                [21, 'NZD'],
                [21, 'PAB'],
                [21, 'PEN'],
                [21, 'PGK'],
                [21, 'PHP'],
                [21, 'PKR'],
                [21, 'PLN'],
                [21, 'PYG'],
                [21, 'QAR'],
                [21, 'RON'],
                [21, 'RSD'],
                [21, 'RUB'],
                [21, 'RWF'],
                [21, 'SAR'],
                [21, 'SBD'],
                [21, 'SCR'],
                [21, 'SEK'],
                [21, 'SGD'],
                [21, 'SHP'],
                [21, 'SLL'],
                [21, 'SOS'],
                [21, 'SRD'],
                [21, 'STD'],
                [21, 'SZL'],
                [21, 'THB'],
                [21, 'TJS'],
                [21, 'TOP'],
                [21, 'TRY'],
                [21, 'TTD'],
                [21, 'TWD'],
                [21, 'TZS'],
                [21, 'UAH'],
                [21, 'UGX'],
                [21, 'UYU'],
                [21, 'UZS'],
                [21, 'VND'],
                [21, 'VUV'],
                [21, 'WST'],
                [21, 'XAF'],
                [21, 'XCD'],
                [21, 'XOF'],
                [21, 'XPF'],
                [21, 'YER'],
                [21, 'ZAR'],
                [21, 'ZMW'],
            ],
        ];
    }
}
