<?php

use Fuel\Core\Response;
use Helpers\StringHelper;

final class WonderlandPaySender extends Helpers_Payment_Sender implements Forms_Wordpress_Payment_Process
{
    const PRODUCTION_URL = 'https://pay.wonderlandpay.com/Interface';
    const TESTING_URL = 'https://pay.wonderlandpay.com/TestInterface';

    public function __construct(
        ?array $whitelabel = [],
        ?array $user = [],
        ?Model_Whitelabel_Transaction $transaction = null,
        ?Model_Whitelabel_Payment_Method $model_whitelabel_payment_method = null
    ) {
        parent::__construct(
            $whitelabel,
            $user,
            $transaction,
            $model_whitelabel_payment_method,
            Helpers_Payment_Method::WONDERLANDPAY_NAME,
            Helpers_Payment_Method::WONDERLANDPAY
        );
    }

    /**
     * Creates data for redirect to payment page with url encoded parameters
     * {@inheritdoc}
     */
    protected function implementation_fetch_transaction_address(array &$log_data): string
    {
        $prefixedTransactionToken = $this->get_prefixed_transaction_token();

        $currencyCode = $this->get_payment_currency($this->transaction->payment_currency_id);

        $resultUrl = $this->get_result_url();

        $fullRequestData = [
            'merNo' => $this->payment_data['wonderlandpay_merchant_number'],
            'gatewayNo' => $this->payment_data['wonderlandpay_gateway_number'],
            'orderNo' => $prefixedTransactionToken,
            'orderCurrency' => $currencyCode,
            'orderAmount' => $this->transaction['amount_payment'],
            'returnUrl' => lotto_platform_home_url_without_language() . $resultUrl,
        ];

        $signature = $this->generateSignatureFromOrderDataUsingSecretKey($fullRequestData, $this->payment_data['wonderlandpay_secret_key']);

        $fullRequestData['notifyUrl'] = $this->getConfirmationFullUrl();
        $fullRequestData['signInfo'] = $signature;

        // Customer info - can be optionally sent to payment gateway to pre-populate payment fields
        $fullRequestData['firstName'] = $this->user['name'] ?? '';
        $fullRequestData['lastName'] = $this->user['surname'] ?? '';
        $fullRequestData['email'] = $this->user['email'] ?? '';
        $fullRequestData['phone'] = $this->user['phone'] ?? '';
        $userAddress = StringHelper::implode(' ', [$this->user['address_1'], $this->user['address_2']]);
        $fullRequestData['address'] = $userAddress ?? '';
        $fullRequestData['zip'] = $this->user['zip'] ?? '';
        $fullRequestData['city'] = $this->user['city'] ?? '';
        $fullRequestData['country'] = $this->user['country'] ?? '';

        $urlEncodedParameters = http_build_query($fullRequestData);
        $isUrlCorrect = !empty($this->payment_url) && !empty($urlEncodedParameters);

        if ($isUrlCorrect) {
            $this->log_info('Payment data was created successfully.', $fullRequestData);
            return $this->payment_url . '?' . $urlEncodedParameters;
        } else {
            $this->log('WonderlandPay sender error: empty baseUri or urlEncodedParameters',
                       Helpers_General::TYPE_ERROR,
                       ['paymentUrl' => $this->payment_url, 'urlEncodedParameters' => $urlEncodedParameters]
            );
        }

        // otherwise set general message
        throw new \Exception('General failure - unable to fetch result, reached last checkpoint');
    }

    public function get_result_url(): string
    {
        $whitelabel_payment_method_id = $this->get_whitelabel_payment_method_id();
        if (empty($whitelabel_payment_method_id)) {
            $this->log_error("Lack of whitelabel_payment_method_id!");
            exit(_("Bad request! Please contact us!"));
        }

        $result_url = Helper_Route::ORDER_RESULT .
            Helpers_Payment_Method::WONDERLANDPAY_URI .
            "/" .
            $whitelabel_payment_method_id .
            "/";

        return $result_url;
    }

    /**
     * Signature is generated by making sha-256 hash of such string:
     * merNo + gatewayNo + orderNo + orderCurrency + orderAmount + returnUrl + signkey;
     * Warning! Do not pass any other data such as order description or items, as it will generate wrong signature.
     * @param array $orderData
     * @param string $projectSecretKey
     * @return string encrypted data
     */
    private function generateSignatureFromOrderDataUsingSecretKey(array $orderData, string $projectSecretKey): string
    {
        return hash('sha256', implode($orderData) . $projectSecretKey);
    }

    public function create_payment(): void
    {
        $payment_address = $this->fetch_transaction_address();
        if ($payment_address === null) { // invalid address
            Response::redirect(lotto_platform_home_url(Helper_Route::ORDER_FAILURE));
        }
        Response::redirect($payment_address); // note: exit is contained here
    }

    /**
     *
     * @param Model_Whitelabel_Transaction $transaction
     * @param string $out_id
     * @param array $data
     * @return void
     */
    public function confirm_payment(
        Model_Whitelabel_Transaction &$transaction = null,
        string &$out_id = null,
        array &$data = []
    ): bool {
        $ok = false;

        return $ok;
    }
}
