<?php

final class Tests_Feature_Controller_Update_Balance_Csv extends Test_Feature
{
    const UPDATE_BALANCE_CSV_ACTION = 'https://empire.whitelotto.loc/dev/update_balance_from_csv';

    const FILENAME = 'balance.csv';

    private $whitelabel;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->whitelabel = Model_Whitelabel::get_single_by_id(1);
    }

    private function generate_csv_file(array $data)
    {
        $fp = fopen(APPPATH . '/tmp/' . self::FILENAME, 'w');
        foreach ($data as $fields) {
            fputcsv($fp, $fields);
        }

        fclose($fp);

        return fopen(APPPATH . '/tmp/' . self::FILENAME, "r");
    }

    /**
     * @param int $rows_count
     * @param string $login_prefix
     * @param int $amount_to_add
     * @param string $currency_code
     * @return string[][]
     */
    private function generate_csv_data(int $rows_count = 10, string $userprefix = 'testuser', $amount_to_add = 100, $currency_code = 'USD'): array
    {
        $data = [ ['no', 'user', 'amount', 'currency_code'] ]; // Add headers
        for ($i = 1; $i <= $rows_count; $i++) {
            $data[] = [$i, (strpos('test@user.loc', '@', 1) ? "$userprefix+$i" : "$userprefix+$i"), $amount_to_add, $currency_code];
        }
        // testuser@test.loc
        return $data;
    }

    private function generate_users(string $prefix = 'testuser', int $users_count = 100, int $whitelabel_id = 1): void
    {
        //Helpers_Cli::execute_or_fail_with_print_output("php oil r dev:generate_users $prefix $users_count $whitelabel_id");
    }

    private function assert_user_balance(): void
    {
//        Model_Whitelabel_User::find([
//            'where' => [
//                'email' => $this->email
//            ]
//        ]);
    }

    private function set_whitelabel_for_test(int $type = 1, float $balance = 10000, int $use_logins = 1, int $unique_emails = 0): void
    {
        $this->whitelabel['type'] = $type;
        $this->whitelabel['user_balance_change_limit'] = $balance;
        $this->whitelabel['use_logins_for_users'] = $use_logins;
        $this->whitelabel['assert_unique_emails_for_users'] = $unique_emails;
    }

    private function post_csv($file, string $is_bonus = 'false', string $whitelabel_name = 'lottopark', string $delimiter =';', string $use_emails = 'true', string $filter_invalid = 'true'): void
    {
        $action_url = self::UPDATE_BALANCE_CSV_ACTION . "?whitelabel_name=$whitelabel_name&delimiter=$delimiter&filter_invalid=$filter_invalid&is_bonus=$is_bonus&use_emails=$use_emails";

        $client = new GuzzleHttp\Client([
            'verify' => false,
            'http_errors' => false
        ]);

        $response = $client->post($action_url, [
            'multipart' => [
                [
                    'name'     => 'file',
                    'contents' => $file,
                    'headers' => [
                        'Content-Type' => 'application/csv',
                    ]
                ],
                [
                    'name'     => 'submit',
                    'contents' => 'Prześlij'
                ],
                [
                    'name'     => 'filename',
                    'contents' => self::FILENAME
                ],
            ]
        ]);
    }

    public function test_update_balance_from_csv_login_success(): void
    {
        $this->generate_users('test_user', 100);

        $this->set_whitelabel_for_test(1, 1000000, 1, 0);

        // Generate CSV data and file
        $data = $this->generate_csv_data(10, 'test_user', 100, 'USD');
        $csv_file = $this->generate_csv_file($data);

        $this->post_csv($csv_file, 'false', 'lottopark', ',', 'false', 'true');
    }

    public function test_update_bonus_balance_from_csv_login_success(): void
    {
        $this->set_whitelabel_for_test(1, 10000, 1, 0);

        // Generate CSV data and file
        $data = $this->generate_csv_data(2, 'testuser', 100, 'USD');
        $csv_file = $this->generate_csv_file($data);

        $this->post_csv($csv_file, 'true', 'lottopark', ',', 'false', 'true');
    }

    public function test_update_balance_from_csv_email_success(): void
    {
        $this->set_whitelabel_for_test(1, 10000, 1, 0);

        // Generate CSV data and file
        $data = $this->generate_csv_data(2, 'testuser@test.loc', 100, 'USD');
        $csv_file = $this->generate_csv_file($data);

        $this->post_csv($csv_file, 'false', 'lottopark', ',', 'false', 'true');
    }

    public function test_update_bonus_balance_from_csv_email_success(): void
    {
        $this->set_whitelabel_for_test(1, 10000, 0, 1);

        // Generate CSV data and file
        $data = $this->generate_csv_data(2, 'testuser', 100, 'USD');
        $csv_file = $this->generate_csv_file($data);

        $this->post_csv($csv_file, 'true', 'lottopark', ',', 'false', 'true');
    }

    public function test_update_balance_from_csv_emailssssssssss_success(): void
    {
        $this->set_whitelabel_for_test(1, 10000, 0, 1);

        // Generate CSV data and file
        $data = $this->generate_csv_data(2, 'testuser', 100, 'USD');
        $csv_file = $this->generate_csv_file($data);

        $this->post_csv($csv_file, 'false', 'lottopark', ',', 'false', 'true');
    }

    public function test_update_balance_from_csv_failure(): void
    {
        $this->markTestIncomplete('in progress');
    }

    public function test_update_bonus_balance_from_csv_failure(): void
    {
        $this->markTestIncomplete('in progress');
    }
}
